#!/usr/bin/env bash

set -o errexit
set -o pipefail

if [ -z "$2" ]; then
    echo "Missing argument. One argument required."
    exit 1
fi

set -o nounset

name="$(gum input --prompt 'Name: ' --value "$2")"

echo "Description:"
description="$(gum write --prompt '| ' --value "$name")"
echo "$description"

gum confirm "Reserve $name on crates.io?"

echo "Reserving '$name' on crates.io..."

dir="$(mktemp -d)"
pushd "$dir"
cat <<EOF > Cargo.toml
[package]
name = "$name"
version = "0.0.1"
description = "$description"
license = "Apache-2.0"
EOF
mkdir src
touch src/lib.rs
cargo publish
popd
