#!/usr/bin/env bash

set -o errexit
set -o pipefail

if [ -z "$1" ]; then
    echo "Missing argument. One argument required."
    exit 1
fi

name="$1"

# If the name is reserve it is being run as `cargo reserve`.
if [[ "$name" == "reserve" ]]; then
    if [ -z "$2" ]; then
        echo "Missing argument. One argument required."
        exit 1
    fi
    name="$2"
fi

set -o nounset

name="$(gum input --prompt 'Name: ' --value "$name")"

echo "Description:"
description="$(gum write --prompt '| ' --value "$name")"
echo "$description"

gum confirm "Reserve $name on crates.io?"

echo "Reserving '$name' on crates.io..."

dir="$(mktemp -d)"
pushd "$dir"
cat <<EOF > Cargo.toml
[package]
name = "$name"
version = "0.0.1"
description = "$description"
license = "Apache-2.0"
EOF
mkdir src
touch src/lib.rs
cargo publish
cargo yank $name --version 0.0.1
popd
