#!/usr/bin/env zsh

set -o nounset

# Create symlink if it doesn't exist.
# Claude Code displays a warning if the binary isn't in that location.
if [ ! -L ~/.local/bin/claude ]; then
  mkdir -p ~/.local/bin
  ln -s "$0" ~/.local/bin/claude
fi

CLAUDE_BIN="$BREW_PREFIX/bin/claude"

if [ $# -eq 0 ]; then
  "$CLAUDE_BIN" --mcp-config "$HOME/.claude/mcp.json"
else
  "$CLAUDE_BIN" "$@"
fi
