#!/usr/bin/env bash

set -o nounset

echo Reminder: This command can only be run from linux, not from macOS.

docker run -it --rm \
  -p 8006:8006 \
  --device=/dev/kvm \
  --device=/dev/net/tun \
  --cap-add NET_ADMIN \
  --stop-timeout 120 \
  dockurr/windows
