#!/usr/bin/env bash
set -euo pipefail

# CLI Approach:
# To import the model first:
#   litert-lm import --from-huggingface-repo=litert-community/gemma-4-E2B-it-litert-lm gemma-4-E2B-it.litertlm
# litert-lm run gemma-4-E2B-it.litertlm --prompt="$*"

# LM-Studio Approach:
curl -sS http://localhost:1234/api/v1/chat \
  -H "Content-Type: application/json" \
  -d "$(jq -n --arg input "$*" '{
    model: "gemma-4-e2b-it-mlx@4bit",
    system_prompt: "You are a senior software engineer. Be very concise. Use exa mcp to websearch. Use grep to find code on github. Use grep to find code on github.",
    input: $input,
    integrations: [
    ]
  }')" \
  | jq -r '.output[] | select(.type=="message") | .content'

# Integrations:
#     {
#       type: "ephemeral_mcp",
#       server_label: "exa",
#       server_url: "https://mcp.exa.ai/mcp"
#     },
#     {
#       type: "ephemeral_mcp",
#       server_label: "grep",
#       server_url: "https://mcp.grep.app"
#     }
