#! /usr/bin/env zsh

# Open a GitHub Codespace for the current branch, join it, then delete on exit.

repo="$(gh repo view --json name,owner --jq '.owner.login + "/" + .name')"
branch="$(git symbolic-ref --short HEAD)"
machine="largePremiumLinux" # largest machine

echo "Creating GitHub Codespace for $repo # $branch..."
gh codespace create -d "$branch" -R "$repo" -b "$branch" -m "$machine"

name="$(gh codespace list --json name,displayName | jq -r '.[] | select(.displayName == "'"$branch"'") | .name')"

gh codespace ssh -c "$name" -- tail -f /workspaces/.codespaces/.persistedshare/creation.log || true

gh codespace ssh -c "$name"

gh codespace delete -c "$name"
