#!/usr/bin/env zsh

set -o nounset

function {
  local branch="$(git rev-parse --abbrev-ref HEAD)"
  if [ -t 1 ] ; then
    if (( $+commands[pbcopy] )); then
      echo -n $branch | pbcopy
    fi
  fi
  echo -n $branch
}
