#!/usr/bin/env zsh

set -o nounset

function {
  local branch="$1"
  local dir="../${PWD##*/}-${branch}"

  git worktree prune
  if git show-ref --verify --quiet "refs/heads/$branch"; then
    git worktree add "$dir" "$branch"
  else
    git worktree add -b "$branch" "$dir"
  fi
} "$@"
