#!/usr/bin/env zsh
# Wrapper script that unsets *_API_KEY and *_TOKEN environment variables before executing a command

for var in ${(k)parameters}; do
    if [[ $var == *_API_KEY || $var == *_TOKEN ]]; then
        unset "$var"
        echo "safeenv: unset $var"
    fi
done

echo "safeenv: starting \"$@\""
exec "$@"
