#!/usr/bin/env bash

set -o nounset

# Inspired by https://github.com/openai/codex/blob/523996b5cb30c2cbf714e61864669f8241f8ec3c/codex-cli/src/utils/agent/sandbox/macos-seatbelt.ts
#
# Original code Copyright 2025 OpenAI
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Also inspired by Chromes sandbox policy:
# https://source.chromium.org/chromium/chromium/src/+/main:sandbox/policy/mac/common.sb;l=273-319;drc=7b3962fe2e5fc9e2ee58000dc8fbf3429d84d3bd
read -r -d '' policy << EOS
(version 1)

; start with closed-by-default
(deny default)

; allow read-only file operations
(allow file-read*)

; child processes inherit the policy of their parent
(allow process-exec)
(allow process-fork)
(allow signal (target self))

(allow file-write-data
  (require-all
    (path "/dev/null")
    (vnode-type CHARACTER-DEVICE)))

; sysctls permitted.
(allow sysctl-read
  (sysctl-name "hw.activecpu")
  (sysctl-name "hw.busfrequency_compat")
  (sysctl-name "hw.byteorder")
  (sysctl-name "hw.cacheconfig")
  (sysctl-name "hw.cachelinesize_compat")
  (sysctl-name "hw.cpufamily")
  (sysctl-name "hw.cpufrequency_compat")
  (sysctl-name "hw.cputype")
  (sysctl-name "hw.l1dcachesize_compat")
  (sysctl-name "hw.l1icachesize_compat")
  (sysctl-name "hw.l2cachesize_compat")
  (sysctl-name "hw.l3cachesize_compat")
  (sysctl-name "hw.logicalcpu_max")
  (sysctl-name "hw.machine")
  (sysctl-name "hw.ncpu")
  (sysctl-name "hw.nperflevels")
  (sysctl-name "hw.optional.arm.FEAT_BF16")
  (sysctl-name "hw.optional.arm.FEAT_DotProd")
  (sysctl-name "hw.optional.arm.FEAT_FCMA")
  (sysctl-name "hw.optional.arm.FEAT_FHM")
  (sysctl-name "hw.optional.arm.FEAT_FP16")
  (sysctl-name "hw.optional.arm.FEAT_I8MM")
  (sysctl-name "hw.optional.arm.FEAT_JSCVT")
  (sysctl-name "hw.optional.arm.FEAT_LSE")
  (sysctl-name "hw.optional.arm.FEAT_RDM")
  (sysctl-name "hw.optional.arm.FEAT_SHA512")
  (sysctl-name "hw.optional.armv8_2_sha512")
  (sysctl-name "hw.memsize")
  (sysctl-name "hw.pagesize")
  (sysctl-name "hw.packages")
  (sysctl-name "hw.pagesize_compat")
  (sysctl-name "hw.physicalcpu_max")
  (sysctl-name "hw.tbfrequency_compat")
  (sysctl-name "hw.vectorunit")
  (sysctl-name "kern.hostname")
  (sysctl-name "kern.maxfilesperproc")
  (sysctl-name "kern.osproductversion")
  (sysctl-name "kern.osrelease")
  (sysctl-name "kern.ostype")
  (sysctl-name "kern.osvariant_status")
  (sysctl-name "kern.osversion")
  (sysctl-name "kern.secure_kernel")
  (sysctl-name "kern.usrstack64")
  (sysctl-name "kern.version")
  (sysctl-name "sysctl.proc_cputype")
  (sysctl-name-prefix "hw.perflevel")
)

; Other options configured
EOS

if [[ "$#" -eq 0 ]]; then
  set -- "help"
fi

# Add directories allowed writing to.
verbose=0
help=0
while [[ "$#" -gt 0 ]]; do 
  case "$1" in
    help|-h|--help)
      help=1
      shift;;

    -v|--verbose)
      verbose=1
      shift;;

    --allow-network)
      policy="$policy
(allow network*)"
      shift;;

    --deny-file-read)
      policy="$policy
(deny file-read* (subpath \"$(realpath $2)\"))"
      shift;shift;;

    --deny-file-write)
      policy="$policy
(deny file-write* (subpath \"$(realpath $2)\"))"
      shift;shift;;

    --allow-file-write)
      policy="$policy
(allow file-write* (subpath \"$(realpath $2)\"))"
      shift;shift;;

    --)
      shift;break;;

    *)
      break;;
  esac
done

if [[ "$help" -eq 1 ]]; then
  >&2 cat <<- EOS
Usage: sandbox [OPTIONS] -- <COMMAND> <ARG>...

Examples:
    sandbox ls
    sandbox --allow-network -- curl -sS https://api.github.com
    sandbox --allow-file-write . -- touch file

Options:
    --allow-network

    --deny-file-read <PATH>

    --allow-file-write <PATH>
    --deny-file-write <PATH>

Use -- to disambiguate options from commands to be executed.
EOS
  if [[ "$verbose" -eq 1 ]]; then
    >&2 cat <<- EOS

Default policy:

$policy
EOS
  fi
  exit
fi

if [[ "$verbose" -eq 1 ]]; then
  >&2 echo ℹ️ Policy:
  >&2 echo "$policy"
  >&2 echo
  >&2 echo ℹ️ Command:
  >&2 echo sandbox-exec -p \"\$policy\" -- $@
fi

sandbox-exec -p "$policy" -- $@
