#! /usr/bin/env zsh

function title {
  print -P "%F{green}$1%f"
}

# Collect user info
title 'Collecting user info...'
name='Leigh McCulloch'
email='leigh@'
vared -p 'Name: ' -c name
vared -p 'Email: ' -c email

# Configure user
title 'Configuring git...'
git config -f "$HOME/.gitconfig.local" user.name "$name"
git config -f "$HOME/.gitconfig.local" user.email "$email"
title 'Done.'
