#! /usr/bin/env zsh

# Open a GitHub Codespace for the current branch, join it, then delete on exit.

repo="$(gh repo view --json name,owner --jq '.owner.login + "/" + .name')"

branch="$(git symbolic-ref --short HEAD)"

machine="largePremiumLinux" # largest machine

echo "Creating GitHub Codespace for $repo # $branch..."
name="$(gh codespace create \
  -d "$branch" \
  -R "$repo" \
  -b "$branch" \
  -m "$machine" \
  | tee /dev/stderr \
  | tail -1\
)"

echo "Tailing creation log..."
echo "Press Ctrl+C to continue to SSH session..."
ssh_pid=""
trap 'kill $ssh_pid 2>/dev/null' INT
gh codespace ssh -c "$name" -- tail -f /workspaces/.codespaces/.persistedshare/creation.log &
ssh_pid=$!
wait $ssh_pid 2>/dev/null
trap - INT

echo "SSHing in..."
gh codespace ssh -c "$name"
