#!/usr/bin/env zsh

# Outputs the go v0.0.0 semantic version for the module in the current
# directory at its current commit.

set -o nounset

function {
  local id="$(git rev-parse HEAD)"
  local ts="$(TZ=UTC git show -s --no-show-signature --format=%cd --date=format-local:'%Y%m%d%H%M%S' HEAD)"
  local ver="v0.0.0-${ts}-${id:0:12}"
  if [ -t 1 ] ; then
    if (( $+commands[pbcopy] )); then
      echo -n $ver | pbcopy
    fi
  fi
  echo -n $ver
}
