model = "gpt-5-codex"
model_reasoning_effort = "low"
model_verbosity = "low"
hide_agent_reasoning = true
file_opener = "none"

experimental_use_rmcp_client = true

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.perplexity]
command = "deno"
args = ["run", "--allow-env=PERPLEXITY_API_KEY,PERPLEXITY_TIMEOUT_MS", "--allow-net=api.perplexity.ai:443", "npm:@perplexity-ai/mcp-server"]
env = { "PERPLEXITY_API_KEY" = "$PERPLEXITY_API_KEY" }

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_PERSONAL_ACCESS_TOKEN"

[mcp_servers.grep]
url = "https://mcp.grep.app"

[mcp_servers.playwright]
command = "deno"
args = ["run", "--allow-env", "--allow-sys", "npm:@playwright/mcp"]
