model = "gpt-5.5"
model_reasoning_effort = "medium"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[projects."/Users/leighmcculloch/Code/one-way-channel"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code/scratch"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code/raw-soroban-inc3"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code/scratch/raw-soroban-inc3"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code/timer"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code/silo"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/Code/leighmcculloch.com"]
trust_level = "trusted"

[projects."/Users/leighmcculloch/.dotfiles"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-04-24T23:22:34Z"
source_type = "local"
source = "/Users/leighmcculloch/.dotfiles/files/codex/.tmp/bundled-marketplaces/openai-bundled"

[tui.model_availability_nux]
"gpt-5.5" = 2
