#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f /usr/bin/crystal ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    curl -fsSL https://crystal-lang.org/install.sh | sudo bash

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
