#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/psql ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  version=12
  echo -e "\033[1;32mInstalling '$me' version $version...\033[0m"

  codename=$(cat /etc/os-release | grep -Po 'VERSION_CODENAME=\K.*')
  echo "deb http://apt.postgresql.org/pub/repos/apt/ $codename-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
  curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  apt-update-if-stale
  sudo apt-get -y install postgresql-client-$version

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
