#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/fly ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -L https://fly.io/install.sh | FLYCTL_INSTALL=$LOCAL sh

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
