#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/"$me" ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    go get -u github.com/onsi/ginkgo/ginkgo
    go get -u github.com/onsi/gomega/...

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
