#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/godoc ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    dir=$(mktemp -d)
    pushd $dir
    go mod init tool
    go get -u golang.org/x/tools/cmd/godoc
    popd
    rm -fr $dir

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
