#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/gcloud ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  # gcloud
  curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-265.0.0-linux-x86_64.tar.gz | tar xz -C $LOCAL
  $LOCAL/google-cloud-sdk/install.sh \
    --usage-reporting false \
    --additional-components beta app-engine-go cloud-datastore-emulator pubsub-emulator \
    --quiet
  ln -sf $LOCAL/google-cloud-sdk/bin/gcloud $LOCAL_BIN/gcloud
  ln -sf $LOCAL/google-cloud-sdk/bin/gsutil $LOCAL_BIN/gsutil

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
