#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/heroku ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  curl -sSL https://cli-assets.heroku.com/heroku-linux-x64.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/heroku/bin/heroku $LOCAL_BIN/heroku

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
