#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/hub ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  curl -sSL https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz | tar xz -C $LOCAL
  ln -sf $LOCAL/hub-linux-amd64-2.12.8/bin/hub $LOCAL_BIN/hub

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
