#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/java ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  apt-update-if-stale
  sudo apt-get -y install default-jdk openjdk-11-source
  sudo ln -s /usr/lib/jvm/openjdk-11/src.zip /usr/lib/jvm/java-1.11.0-openjdk-amd64/src.zip || true
  sudo ln -s /usr/lib/jvm/openjdk-11/lib/src.zip /usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/src.zip || true

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
