#!/usr/bin/env zsh

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/keybase ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  dir="$(mktemp -d)"
  curl -o "$dir/keybase_amd64.deb" https://prerelease.keybase.io/keybase_amd64.deb
  sudo apt-get -y install "$dir/keybase_amd64.deb"
  rm -fr $dir

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
