#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/kubectl ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  version="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
  echo -e "\033[1;32mInstalling '$me' version '$version'...\033[0m"
  url="https://storage.googleapis.com/kubernetes-release/release/$version/bin/linux/amd64/kubectl"
  curl -L "$url" -o $LOCAL_BIN/kubectl
  chmod +x $LOCAL_BIN/kubectl

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
