#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL/apache-maven-3.6.0/bin/mvn ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  curl -sSL http://mirrors.koehn.com/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz | tar xz -C $LOCAL

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$LOCAL/apache-maven-3.6.0/bin/mvn" "$@"
