#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
set -m

me="$(basename "$0")"

if ! [ -f /usr/sbin/mysqld ] ; then
  echo -e "\033[1;32mInstalling '$me'...\033[0m"
  sudo apt-get -y install mariadb-server
  sudo mkdir -p /var/run/mysqld
  sudo chown -R mysql:mysql /var/run/mysqld
  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

sudo -u mysql mysqld --skip-grant-tables &
