#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/pandoc ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  sudo apt-get -y install pandoc

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
