#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/pip3 ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  python3 -V
  apt-update-if-stale
  sudo apt-get -y install python3-pip

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

pip3 "$@"
