#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

if ! [ -f /usr/games/sl ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  sudo apt-get -y install sl

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

/usr/games/sl -e "$@"
