#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/stc ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  dir=$(mktemp -d)
  pushd $dir
  git clone -b cap21 https://github.com/leighmcculloch/xdrpp--stc stc
  cd stc
  make depend
  make
  make install PREFIX=$LOCAL
  popd
  rm -fr $dir

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
