#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/sudo ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  apt-get update
  apt-get install -y sudo

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
