#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -d $LOCAL_BIN/tinkey ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  version=1.4.0
  curl https://storage.googleapis.com/tinkey/tinkey-linux-x86_64-$version.tar.gz | tar xz -C $LOCAL_BIN

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
