#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $HOME/.local/bin/twtxt ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  pip3 install twtxt

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
