#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f "/usr/bin/vim" ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  apt-update-if-stale
  sudo apt-get install -y vim

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"

  # install vim plugins
  vim +PlugInstall +qa
fi

"$me" "$@"
