#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f /usr/bin/xz ] ; then
    echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

    apt-update-if-stale
    sudo apt-get -y install xz-utils

    echo -e "\e[1;32mFinished installing '$me'.\e[0m"
  fi
} 1>&2

"$me" "$@"
