#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  version="master"
  info=$(curl -s https://ziglang.org/download/index.json | jq -r .\""$version"\")
  tarball=$(echo $info | jq -r '."x86_64-linux".tarball')
  if [ "$version" = "master" ] ; then
    version=$(echo $info | jq -r '.version')
  fi

  if ! [ -f $LOCAL_BIN/zig ] ; then
    echo -e "\033[1;32mInstalling '$me' '$version' on first use...\033[0m"

    curl -sSL $tarball | tar xJ -C $LOCAL
    ln -sf $LOCAL/zig-linux-x86_64-$version/zig $LOCAL_BIN/zig

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
