#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/zls ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  version=0.1.0
  curl -sSL https://github.com/zigtools/zls/releases/download/$version/x86_64-linux.tar.xz | tar xJ -C $LOCAL
  ln -sf $LOCAL/x86_64-linux/zls $LOCAL_BIN/zls

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

"$me" "$@"
