install:
	$(MAKE) -C menu-bar-usage-codex install
	$(MAKE) -C paste-markdown install
	$(MAKE) -C paste-pr install
	$(MAKE) -C qr-reader install
	$(MAKE) -C github-events install
	$(MAKE) -C stopwatch install
	$(MAKE) -C app-scheduler install
