brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gum"
brew "httpie"
brew "jless"
brew "jq"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "tree"
brew "prettier"
brew "eza"

brew "rustup"
brew "go"
brew "deno"
brew "node"

brew "neovim"
brew "gopls"
brew "vscode-langservers-extracted"

go "github.com/leighmcculloch/gas/v3"

if OS.mac?
  brew "leighmcculloch/silo/silo", args: ["HEAD"], trusted: true

  brew "stellar-cli"
  brew "autoconf"
  brew "automake"
  brew "clang-format"
  brew "cmake"
  brew "coreutils"
  brew "docker"
  brew "docker-buildx"
  brew "ffmpeg"
  brew "imagemagick"
  brew "wabt"
  brew "container"
  brew "rtk"

  cask "chatgpt"
  cask "claude"
  cask "github-copilot-app"
  cask "obsidian"
  cask "font-fira-code"
  cask "font-fira-code-nerd-font"
  cask "orbstack"
  cask "discord"
  cask "ghostty"
  cask "sublime-text"
  cask "lm-studio"
  cask "voiceink"
  cask "thebrowsercompany-dia"
  cask "screen-studio"

  brew "mas"
  mas "Day Progress", id: 6450280202

  mdm_enrolled = `profiles status -type enrollment`.include?("Yes")

  if mdm_enrolled
    cask "nordlayer"
    cask "gcloud-cli"
  else
    cask "nordvpn"
    cask "doxie"
    brew "cloudflare-wrangler"
    mas "Prime Video", id: 545519333
    mas "WhatsApp", id: 310633997
  end
end
