call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'nvim-tree/nvim-tree.lua'
Plug 'vim-scripts/vim-auto-save'
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'
Plug 'github/copilot.vim'
Plug 'haya14busa/incsearch.vim'
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lualine/lualine.nvim'
Plug 'nvim-tree/nvim-web-devicons'
Plug 'preservim/vim-markdown'
Plug 'sheerun/vim-polyglot'
Plug 'akinsho/bufferline.nvim', { 'tag': '*' }

" Completion
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'

" Themes
Plug 'sainnhe/sonokai'

" For rust
Plug 'rust-lang/rust.vim'
call plug#end()

runtime vimrc.lock

filetype plugin on

set nomore
set termguicolors

set background=dark
silent! colorscheme sonokai

let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1

set backspace=indent,eol,start

set number

autocmd FileType * setlocal expandtab shiftwidth=2 softtabstop=2 tabstop=2
autocmd FileType go setlocal noexpandtab shiftwidth=4 softtabstop=4 tabstop=4
autocmd FileType make setlocal noexpandtab shiftwidth=4 softtabstop=4 tabstop=4

" Navigating within wrapped lines
noremap <silent> k gk
noremap <silent> j gj
noremap <silent> 0 g0
noremap <silent> $ g$

" CTRL-H/J/K/L in popups
inoremap <expr> <c-j> (pumvisible()?"\<C-n>":"\<c-j>")
inoremap <expr> <c-k> (pumvisible()?"\<C-p>":"\<c-k>")

" CTRL-H/L to iterate through buffers
noremap <c-h> :bprev<CR>
noremap <c-l> :bnext<CR>

" CTRL-J/K to iterate through quickfix list errors
noremap <c-k> :cprev<CR>
noremap <c-j> :cnext<CR>

" Iterate through location list
nmap cn :lnext<cr>
nmap cp :lprevious<cr>

" CTRL-P mapping to fzf
noremap <c-p> :FZF<CR>

" CTRL-Q to delete a buffer
noremap <c-q> :bdelete<CR>

" Pasting retaining register
xnoremap <expr> p 'pgv"'.v:register.'y'

" Search with ripgrep
if executable('rg')
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
  set grepformat+=%f:%l:%c:%m
endif

" Search word under cursor
nnoremap <leader>gw :Ggrep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Start search for word case insensitive
nnoremap <C-f> :Ggrep! -i 

" Auto open quickfix window
augroup quickfix
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost l* lwindow
augroup END

" Incremental search
map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
set hlsearch
let g:incsearch#auto_nohlsearch = 1
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
let g:auto_save_silent = 1
let g:auto_save_no_updatetime = 0

imap <m-i> <Plug>(copilot-suggest)
imap <m-j> <Plug>(copilot-next)
imap <m-k> <Plug>(copilot-previous)
imap <m-l> <Plug>(copilot-accept-word)

nmap <c-e> :NvimTreeFindFile<cr>

au FileType rust nmap <buffer> tt :RustTest<CR>
