#!/usr/bin/env zsh

# Stop hook, wired up via claude-cloud/settings.json. However a PR gets opened
# this session — the /pr skill's `gh`, the GitHub MCP tools, or a raw gh call —
# the cloud integration auto-appends a "Generated by Claude Code" trailer to its
# description. This finds the current branch's PR and strips that trailer out.
#
# It is fail-safe by design: no errexit, and every step that can fail ends in
# `|| exit 0`, so a missing gh, no auth, no PR for the branch, or no trailer all
# just exit cleanly and never block or break a routine Stop.

set -o pipefail
set -o nounset

# Claude Code passes the Stop event as JSON on stdin. Drain it so the pipe closes
# cleanly; nothing in it is needed here.
cat >/dev/null

# gh is the only way a shell hook can read and write the PR body. If it isn't
# installed there is nothing to do.
command -v gh >/dev/null 2>&1 || exit 0

# Resolve the PR for the checked-out branch. `gh pr view` exits non-zero when the
# branch has no PR (or gh can't authenticate), so that path just exits 0.
body=$(gh pr view --json body --jq '.body' 2>/dev/null) || exit 0

# Strip a trailing "Generated by Claude Code" trailer: optional blank lines, a
# `---` rule, then the italic _Generated by [Claude Code](<url>)_ line and any
# trailing whitespace. Anchored to the end (\z) so a `---` rule used elsewhere in
# the body is left alone. perl -0777 slurps the whole body so the pattern spans
# lines; \r? tolerates the CRLF line endings the GitHub API returns.
stripped=$(print -rn -- "$body" | perl -0777 -pe \
  's/[ \t]*\r?\n(?:[ \t]*\r?\n)*---[ \t]*\r?\n_Generated by \[Claude Code\]\([^)]*\)_[ \t\r\n]*\z//') \
  || exit 0

# No trailer matched: leave the PR untouched. RHS is quoted so zsh compares it
# literally rather than as a glob pattern.
[[ "$stripped" == "$body" ]] && exit 0

# Write the cleaned body back. --body-file - reads it from stdin, sidestepping any
# quoting or argument-length limits a long description could hit.
print -rn -- "$stripped" | gh pr edit --body-file - >/dev/null 2>&1 || exit 0
