#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/act ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    # This unreleased version has support for composite actions.
    go install github.com/nektos/act@v0.2.26-0.20220215200300-ff13844b8643

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
