#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

os="$(uname -s -m)"
location=
case $os in
  "Darwin x86_64"*) location=/usr/local/bin/brew ;;
  "Darwin arm64"*) location=/opt/homebrew/bin/brew ;;
  "Linux"*) location=/home/linuxbrew/.linuxbrew/bin/brew ;;
  *) echo "Unrecognized operating system: $(uname)"; exit 1 ;;
esac
if ! [ -f $location ] ; then
  echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  echo 'eval "$($location shellenv)"' >> "$HOME/.zprofile"

  echo -e "\033[1;32mFinished installing '$me'.\033[0m"
fi

eval "$($location shellenv)"
"$me" "$@"
