#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

os="$(uname)"
location=
case $os in
  Linux*)  location=/home/linuxbrew/.linuxbrew/bin/brew ;;
  Darwin*) location=/usr/local/bin/brew ;;
  *) echo "Unrecognized operating system: $(uname)"; exit 1 ;;
esac
if ! [ -f $location ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
