#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $HOME/.cargo/bin/"$me" ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    cargo install --locked --version 0.1.3 cargo-http-registry

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
