#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/crystal ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -fsSL https://crystal-lang.org/install.sh | sudo bash

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
