#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  case $os in
    Darwin*)
      if ! [ -f "$(brew --prefix)"/bin/crystal ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install crystal

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    Linux*)
      if ! [ -f /usr/bin/crystal ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        curl -fsSL https://crystal-lang.org/install.sh | sudo bash

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"

