#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  case $os in
    Darwin*)
      if ! [ -f $LOCAL_BIN/dapr ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        curl -sSL https://github.com/dapr/cli/releases/download/v1.4.0/dapr_darwin_amd64.tar.gz | tar xz -C $LOCAL_BIN dapr

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    Linux*)
      if ! [ -f $LOCAL_BIN/dapr ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        curl -sSL https://github.com/dapr/cli/releases/download/v1.4.0/dapr_linux_amd64.tar.gz | tar xz -C $LOCAL_BIN dapr

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
