#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  case $os in
    Darwin*)
      if ! [ -f "$(brew --prefix)"/bin/docker ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install docker

        mkdir -p "$HOME/.docker/cli-plugins"
        curl -L -o "$HOME/.docker/cli-plugins/docker-buildx" https://github.com/docker/buildx/releases/download/v0.7.0/buildx-v0.7.0.darwin-amd64
        chmod +x "$HOME/.docker/cli-plugins/docker-buildx"

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    Linux*)
      if ! [ -f /usr/bin/docker ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        os=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
        echo -e "\033[1;32mInstalling '$me' for '$os'...\033[0m"

        apt-update-if-stale
        sudo apt-get install ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update
        sudo apt-get -y install docker-ce-cli

        mkdir -p "$HOME/.docker/cli-plugins"
        curl -sSL -o "$HOME/.docker/cli-plugins/docker-buildx" https://github.com/docker/buildx/releases/download/v0.7.0/buildx-v0.7.0.linux-amd64
        chmod +x "$HOME/.docker/cli-plugins/docker-buildx"

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
