#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  case $os in
    Darwin*)
      if ! [ -f /usr/local/bin/docker ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install docker

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    Linux*)
      if ! [ -f /usr/bin/docker ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        os=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
        echo -e "\033[1;32mInstalling '$me' for '$os'...\033[0m"

        apt-update-if-stale
        sudo apt-get -y install \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
        curl -fsSL https://download.docker.com/linux/${os}/gpg \
          | sudo apt-key add -
        sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/${os} \
          $(lsb_release -cs) \
          stable"
        sudo apt update
        sudo apt-get -y install docker-ce-cli

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
