#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  case $os in
    Darwin*)
      if ! [ -f /usr/local/bin/elixir ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install elixir

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    Linux*)
      if ! [ -f /usr/bin/elixir ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        dir=$(mktemp -d)
        pushd "$dir"
        curl -O https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
        sudo apt-get update
        sudo dpkg -i erlang-solutions_2.0_all.deb
        sudo apt-get install esl-erlang
        sudo apt-get install elixir

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
