#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  name=""
  case $os in
    Darwin*) name=macos ;;
    Linux*) name=linux ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
  if ! [ -f $LOCAL_BIN/firebase ] ; then
    echo -e "\033[1;32mInstalling '$me' ($name) on first use...\033[0m"

    curl -Lo $LOCAL_BIN/firebase "https://firebase.tools/bin/$name/latest"
    chmod +x $LOCAL_BIN/firebase

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
