#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $HOME/.cargo/bin/"$me" ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    cargo +nightly install --git https://github.com/dimensionhq/fleet --rev 974d781cc4b09a6617cc7bebedb22dbb48984cf7 fleet-rs

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
