#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/fly ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    dir=$(mktemp -d)
    git clone -b v0.0.262 https://github.com/superfly/flyctl $dir
    pushd $dir
    go build -o $LOCAL_BIN/fly
    popd
    rm -fr $dir

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
