#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/fx ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    go install github.com/antonmedv/fx@v0.0.0-20230920142740-0d636cc6b375

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
