#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/gh ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  codename=$(cat /etc/os-release | grep -Po 'VERSION_CODENAME=\K.*')
  echo "deb https://cli.github.com/packages $codename main" | sudo tee /etc/apt/sources.list.d/github.list
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
  sudo apt update
  sudo apt install gh

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
