#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/gron ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    go install github.com/tomnomnom/gron@v0.7.1

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
