#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $HOME/.cargo/bin/hx ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    cargo install helix-term \
      --locked \
      --git https://github.com/helix-editor/helix \
      --rev 5b1113766d5363c2e434ab596fcca64a1c707a55

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
