#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/lazygit ] ; then
    echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

    go install github.com/jesseduffield/lazygit@f44ae68e99386d5351d7cdec05a3231aa01a2d84

    echo -e "\e[1;32mFinished installing '$me'.\e[0m"
  fi
} 1>&2

"$me" "$@"
