#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -d "$HOME/.nvm" ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    git clone -b v0.39.2 https://github.com/nvm-sh/nvm.git "$HOME/.nvm"

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

. "$HOME/.nvm/nvm.sh"

"$me" "$@"
