#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  location=
  case $os in
    Darwin*)
      if ! [ -f "$(brew --prefix)"/bin/podman ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install podman
        echo -e "\033[1;32mInitializing podman machine...\033[0m"
        podman machine init
        echo -e "\033[1;32mStarting podman machine...\033[0m"
        podman machine start
        echo -e "\033[1;32mWriting ~/.zenv_podman for podman...\033[0m"
        echo "export DOCKER_HOST='unix:///$HOME/.local/share/containers/podman/machine/podman-machine-default/podman.sock'" > $HOME/.zenv_podman

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
