#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f "$HOME"/.local/share/ponyup/bin/"$me" ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    brew install libressl
    sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
    ponyup update ponyc release
    ponyup update corral release

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
