#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $HOME/.local/bin/present ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  pip install present

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
