#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $HOME/.cargo/bin/"$me" ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    # Rustup will detect the rustc and cargo symlinks that exist in lazybin and
    # think they are an existing installation of rust. In response it will
    # prevent a large warning and say it doesn't think it can install rust.  This
    # environment variable will cause the check to be skipped. The code that uses
    # it says it is only intended to be used for tests, so it might go away
    # sometime, but for now this gets the job done.
    # https://github.com/rust-lang/rustup/blob/22dc71adbd7e19de0090f991b3609e5f14910dcb/src/cli/self_update.rs#L415-L435
    export RUSTUP_INIT_SKIP_PATH_CHECK=yes

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path

    rustup update stable
    rustup update nightly

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
