#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/rust-analyzer ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-aarch64-apple-darwin.gz | gunzip -c - > $LOCAL_BIN/rust-analyzer
    chmod +x $LOCAL_BIN/rust-analyzer

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
