#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname -s)"
  case $os in
    Darwin*)
      if ! [ -f "$(brew --prefix)"/bin/sccache ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install sccache
        echo "export RUSTC_WRAPPER=\"$(which sccache)\"" > $HOME/.zenv_sccache

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
