#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  location=
  case $os in
    Darwin*)
      if ! [ -f /usr/local/bin/stdsplit ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        brew install 4d63/stdsplit/stdsplit

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
