#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f "/usr/bin/tmux" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  apt-update-if-stale
  sudo apt-get install -y tmux

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"

  # install tmux plugins if present
  if [ -f "$HOME/.tmux/plugins/tpm/bin/install_plugins" ] ; then
    $HOME/.tmux/plugins/tpm/bin/install_plugins
  fi
fi

"$me" "$@"
