#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL/v/v ] ; then
    echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

    git clone https://github.com/vlang/v $LOCAL/v
    make -C $LOCAL/v

    echo -e "\e[1;32mFinished installing '$me'.\e[0m"
  fi
} 1>&2

"$me" "$@"
