#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -d $LOCAL_BIN/vale ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    tmp=$(mktemp)
    curl -sSL -o "$tmp" https://github.com/ValeLang/Vale/releases/download/v0.2.0/Vale-Mac-0.2.0.28.zip
    unzip -d $LOCAL_BIN/vale "$tmp"

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
