#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

vimnox="/usr/bin/vim.nox"

if ! [ -d "$vimnox" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  sudo apt-get update
  sudo apt-get install -y vim-tiny

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
  
  # install vim plugins
  vim +PlugInstall +qa
  vim +GoInstallBinaries +qa
fi

"$me" "$@"
