#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL/vls/vls ] ; then
    echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

    rm -fr $LOCAL/vls
    git clone https://github.com/vlang/vls $LOCAL/vls
    v -prod $LOCAL/vls/cmd/vls

    echo -e "\e[1;32mFinished installing '$me'.\e[0m"
  fi
} 1>&2

"$me" "$@"
