#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  os="$(uname)"
  case $os in
    Darwin*)
      if ! [ -f $LOCAL_BIN/vmcli ] ; then
        echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

        dir="$(mktemp -d)"
        git clone -b v1.0.3 https://github.com/gyf304/vmcli "$dir"
        pushd "$dir"
        git checkout 5aa60bb6228889d835aa59138023e786426e83c3
        make
        make install PREFIX=$LOCAL
        popd
        rm -fr "$dir"

        echo -e "\033[1;32mFinished installing '$me'.\033[0m"
      fi
    ;;
    *)
      echo "Unrecognized operating system: $(uname)"
      exit 1
    ;;
  esac
} 1>&2

"$me" "$@"
