#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/gopls ] ; then
    echo -e "\033[1;32mInstalling 'gopls' on first use...\033[0m"
    go install golang.org/x/tools/gopls@latest
    echo -e "\033[1;32mFinished installing 'gopls'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/gopkgs ] ; then
    echo -e "\033[1;32mInstalling 'gopkgs' on first use...\033[0m"
    go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
    echo -e "\033[1;32mFinished installing 'gopkgs'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/go-outline ] ; then
    echo -e "\033[1;32mInstalling 'go-outline' on first use...\033[0m"
    go install github.com/ramya-rao-a/go-outline@latest
    echo -e "\033[1;32mFinished installing 'go-outline'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/gotests ] ; then
    echo -e "\033[1;32mInstalling 'gotests' on first use...\033[0m"
    go install github.com/cweill/gotests/gotests@latest
    echo -e "\033[1;32mFinished installing 'gotests'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/gomodifytags ] ; then
    echo -e "\033[1;32mInstalling 'gomodifytags' on first use...\033[0m"
    go install github.com/fatih/gomodifytags@latest
    echo -e "\033[1;32mFinished installing 'gomodifytags'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/impl ] ; then
    echo -e "\033[1;32mInstalling 'impl' on first use...\033[0m"
    go install github.com/josharian/impl@latest
    echo -e "\033[1;32mFinished installing 'impl'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/goplay ] ; then
    echo -e "\033[1;32mInstalling 'goplay' on first use...\033[0m"
    go install github.com/haya14busa/goplay/cmd/goplay@latest
    echo -e "\033[1;32mFinished installing 'goplay'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/dlv ] ; then
    echo -e "\033[1;32mInstalling 'dlv' on first use...\033[0m"
    go install github.com/go-delve/delve/cmd/dlv@master
    echo -e "\033[1;32mFinished installing 'dlv'.\033[0m"
  fi
  if ! [ -f $LOCAL_BIN/golangci-lint ] ; then
    echo -e "\033[1;32mInstalling 'golangci-lint' on first use...\033[0m"
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    echo -e "\033[1;32mFinished installing 'golangci-lint'.\033[0m"
  fi
} 1>&2

"$me" "$@"
