#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL/wasmer/bin/wasmer ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    export WASMER_DIR="$LOCAL/wasmer"
    curl https://get.wasmer.io -sSfL | sh
    echo 'source "$LOCAL/wasmer/wasmer.sh"' > $HOME/.zenv_wasmer

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

$LOCAL/wasmer/bin/wasmer "$@"
