#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! (npm list -g --json wrangler | jq -e '.dependencies | has("wrangler")' > /dev/null) ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    npm install -g wrangler

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

nvm use node
"$me" "$@"
