#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/zig ] ; then
    release="master"
    info=$(curl -s https://ziglang.org/download/index.json | jq -r .\""$release"\")
    version=$(echo $info | jq -r '.version')
    arch=
    os=
    case "$(uname)" in
      Darwin*)
        arch=x86_64
        os=macos
      ;;
      Linux*)
        arch=x86_64
        os=linux
      ;;
      *)
        echo "Unrecognized operating system: $(uname)"
        exit 1
      ;;
    esac

    echo -e "\033[1;32mInstalling '$me' $arch $os $version on first use...\033[0m"

    tarball=$(echo $info | jq -r ".\"$arch-$os\".tarball")
    curl -sSL "$tarball" | tar xJ -C "$LOCAL"
    ln -sf "$LOCAL/zig-$os-$arch-$version/zig" "$LOCAL_BIN/zig"

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
