#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

{
  if ! [ -f $LOCAL_BIN/zls ] ; then
    echo -e "\033[1;32mInstalling '$me' on first use...\033[0m"

    dir="$(mktemp -d)"
    pushd $dir
    git clone --recurse-submodules https://github.com/zigtools/zls
    pushd zls
    zig build --prefix "$LOCAL" -Drelease-safe
    popd
    rm -fr "$dir"

    # Link the ZLS bin into a directory that is always on the PATH, even in
    # situations where the PATH hasn't been configured for some obscure reason.
    # This allows for instructing the VSCode ZLS extension to find the zls
    # executable with simply "zls".
    ln -sf $LOCAL_BIN/zls /usr/local/bin/zls

    echo -e "\033[1;32mFinished installing '$me'.\033[0m"
  fi
} 1>&2

"$me" "$@"
