# path reset on new shells
[ -z "${ORIGINAL_PATH:-}" ] && export ORIGINAL_PATH=$PATH
export PATH=$ORIGINAL_PATH

# helper paths
export DOTFILES="$HOME/.dotfiles"
export LAZYBIN="$HOME/.lazybin"
export LAZYBIN_LINUX="$HOME/.lazybin-linux"
export SCRIPTS="$HOME/.scripts"
export LOCAL="$HOME/.local"
export LOCAL_BIN="$LOCAL/bin"
mkdir -p "$LOCAL_BIN"
mkdir -p "$LAZYBIN"

# for folders supplied by dotfiles
export PATH="$PATH:$SCRIPTS:$LOCAL_BIN"

# for sublime on mac
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
# for vim
export EDITOR=vim
# for go
export PATH="$PATH:$LOCAL_BIN/go/latest/bin"
export GOPATH="$LOCAL/gopath"
export GOBIN=$LOCAL_BIN
export CGO_ENABLED=1
# for v
export PATH="$PATH:$LOCAL/v"
# for ruby
if [[ -f $LOCAL_BIN/rbenv ]]; then
  export RBENV_ROOT=$(dirname $(dirname $(readlink -n $(which rbenv))))
  eval "$(rbenv init -)"
fi
# for python
export PATH="$PATH:$HOME/.local/bin"
# for yarn
export PATH="$PATH:$HOME/.yarn/bin"
# for rust
export PATH="$PATH:$HOME/.cargo/bin"
# for java
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH=$PATH:$LOCAL/apache-maven-3.6.0/bin
# for dotnet
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools"
# for nvm/node
export NVM_DIR="$HOME/.nvm"
# for postgres running in docker
export PGHOST=localhost
export PGUSER=${USER:-$(whoami)}
# for homebrew
export HOMEBREW_NO_ANALYTICS=1
# for homebrew (linux)
export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
# for homebrew (macos intel)
export PATH=/usr/local/bin:$PATH
# for homebrew (macos silicon)
export PATH=/opt/homebrew/bin:$PATH
# for vscode
if [ -d $HOME/.vscode-server ]; then
  for vscodeServerPath in $HOME/.vscode-server/bin/*/bin; do
    export PATH="$PATH:$vscodeServerPath"
    break
  done
fi
# for docker to use buildkit
export DOCKER_BUILDKIT=1
# for vmcli
export VMCTLDIR="$HOME/VMs"
# for dart
export PATH="$PATH:$HOME/.pub-cache/bin"

# for lib packages if installed via homebrew
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(brew --prefix)/opt/libpq/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(brew --prefix)/opt/openssl@3/lib/pkgconfig"

# for folders supplied by dotfiles (must be last)
export PATH="$PATH:$LAZYBIN"
if [ "$(uname)" = "Linux" ]; then
  export PATH="$PATH:$LAZYBIN_LINUX"
fi
