if [ "$ZPROF" ]; then
  zmodload zsh/zprof
fi

# make c-p/c-n work exactly like up/down arrows
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# free up the c-q shortcut for use in vim
stty start undef

source ~/.zenv

# oh-my-zsh
if [ -z "$NOOMZ" ]; then
  export ZSH=$HOME/.oh-my-zsh
  DISABLE_AUTO_UPDATE="true"
  #if [[ "$TERM_PROGRAM" == "ghostty" ]]; then
  #  ZSH_TMUX_AUTOSTART=true
  #  ZSH_TMUX_AUTOQUIT=false
  #  ZSH_TMUX_UNICODE=true
  #fi
  ZSH_CUSTOM="$DOTFILES/files/oh-my-zsh-custom"
  ZSH_THEME="minimal"
  plugins=(zsh-interactive-cd)
  if (( $+commands[git] )); then plugins+=(git git-prompt gitfast) fi
  if (( $+commands[gh] )); then plugins+=(gh) fi
  if (( $+commands[fzf] )); then plugins+=(fzf) fi
  #if (( $+commands[tmux] )); then plugins+=(tmux) fi
  if (( $+commands[http] )); then plugins+=(httpie) fi
  if (( $+commands[rustc] )); then plugins+=(rust) fi
  if (( $+commands[stellar] )); then plugins+=(stellar) fi
  source $ZSH/oh-my-zsh.sh
fi

if [[ -z "$ZELLIJ" && "$TERM_PROGRAM" == "ghostty" ]]; then
  zellij attach -c main
fi
if [[ -n "$ZELLIJ" ]]; then
  zellij_tab_name_update() {
    zellij action rename-tab "$(basename "${PWD/#$HOME/~}")" >/dev/null 2>&1
  }
  zellij_tab_name_update
  chpwd_functions+=(zellij_tab_name_update)
fi

# Use a simplified prompt when recording in asciinema
if [ $ASCIINEMA_REC ]; then
  PROMPT="$ "
fi

# tmux
alias t=tmux
if [ "$TMUX" ]; then
  alias clear="tmux send-keys C-l \; send-keys -R \; clear-history"
fi

# neovim
if (( $+commands[nvim] )); then
  alias vim=nvim
fi

function git() {
  command git config core.hooksPath no-hooks
  command git $@
}

# general aliases
alias l="ls -lah"
alias p="deno run --allow-env=PERPLEXITY_API_KEY --allow-net=api.perplexity.ai:443 jsr:@leigh/perplexity-cli"

# git aliases (in addition to oh-my-zsh git plugin)
unalias gc >/dev/null 2>&1
alias gcy="gc -y"
alias gcyp="gcy && gp"
alias ga.="git add ."
alias gap="git add -p"
alias gacn!="ga. && gcn!"
alias gac="ga. && gc -y"
alias gacp="ga. && gc -y && gp"
alias gaacyp="gaa && gcy && gp"
alias gb="git branch"
alias gde="git diff --exit-code"
alias gdcsv="git diff --color-words=\"[^[:space:],]+\""
alias gdcacsv="git diff --cached --color-words=\"[^[:space:],]+\""
alias gscsv="git show --color-words=\"[^[:space:],]+\""
alias gacnf!="ga . && gcn! && gp -f"
alias gs="git stash"
alias gsp="git stash pop"
alias gsl="git stash list"
alias gupp="gup && gp"
alias gwa="git worktree add"
alias gwau='() { dir="../${PWD##*/}-${@}" ; git worktree prune ; git worktree add "$dir" && cd "$dir" ; }'
alias gwr="git worktree remove"
alias gwl="git worktree list"
alias gwp="git worktree prune"
alias grbs="git rebase --exec 'git commit --amend --no-edit -n -S' -i"

alias ghco="gh co"
alias ghprme="gh pr list --author @me"
alias ghprco="gh pr checkout"

# zsh opts
unsetopt HIST_VERIFY

# print exit code once after last command output
#function track-exec-command() {
#  zsh_exec_command=1
#}
#function print-exit-code() {
#  local -i code=$?
#  (( code == 0 )) && return
#  (( zsh_exec_command != 1 )) && return
#  unset zsh_exec_command
#  print -rC1 -- ''${(%):-"%F{160}✘ exit status $code%f"}''
#}
#autoload -Uz add-zsh-hook
#add-zsh-hook preexec track-exec-command
#add-zsh-hook precmd print-exit-code

# Bell on every new prompt. (See tmux config, which silences it on the active window.)
precmd() { print -n '\a' }

eval "$(starship init zsh)"

if [ "$ZPROF" ]; then
  zprof
fi
